version: '3.8'

services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: testinsights
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
      allow-public-key-retrieval: "true"
    ports:
      - "3306:3306"
    volumes:
      - ./init-scripts:/docker-entrypoint-initdb.d

  test-rep-server:
    image: node:latest
    working_dir: /app
    volumes:
      - ./backend:/app
    ports:
      - "3001:3001"
    command: sh -c "npm install && npm start"

  test-rep-ui:
    image: node:latest
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    command: sh -c "npm install && npm run dev"