version: '3.8'

services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: testinsights
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
      allow-public-key-retrieval: "true"
    ports:
      - "3306:3306"
    volumes:
      - ./init-scripts:/docker-entrypoint-initdb.d
      - mysql_data:/var/lib/mysql

  test-rep-server:
    image: node:latest
    working_dir: /app
    volumes:
      - ./backend:/app
    ports:
      - "3001:3001"
    command: sh -c "npm install && npm start"
    environment:
      DB_USER: admin
      DB_PASSWORD: password
      DB_NAME: testinsights
      SESSION_SECRET: 7aBnK3sPvXgF1hR2mY4zL8wQ

  test-rep-ui:
    image: node:latest
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    command: sh -c "npm install && npm run dev"

volumes:
  mysql_data:
