name: Compare Branches

on:
  workflow_call:
    inputs:
      pr_number:
        required: true
        type: number

jobs:
  compare-pr-results:
    name: Compare PR Branch to Primary
    runs-on: self-hosted
    steps:
      - name: Get Repo Name
        id: repo
        run: echo ::set-output name=repo::${GITHUB_REPOSITORY#$GITHUB_REPOSITORY_OWNER/}
      - name: Get Branch Name
        id: branch
        run: echo ::set-output name=branch::${{ github.head_ref }}
      - name: Install JQ
        run: |
          sudo apt-get update
          sudo apt-get install jq
      - name: Compare Branches
        run: |
          result=$(curl --location 'http://localhost:3001/${{ steps.repo.outputs.repo }}/${{ steps.branch.outputs.branch }}/compare' \
            --header 'x-organization-uuid: ${{ secrets.ORGANIZATION_UUID }}')
          echo "$result" | jq . > result.json
      - name: Comment on PR
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs');
            const parsedResults = fs.readFileSync('result.json', 'utf8');
            github.rest.issues.createComment({
              issue_number: ${{ inputs.pr_number }},
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `Branch comparison results: ${parsedResults}`
            })
