name: Compare Branches

on:
  workflow_call:

jobs:
  compare-pr-results:
    name: Compare PR Branch to Primary
    runs-on: self-hosted
    steps:
      - name: Get Repo Name
        id: repo
        run: echo ::set-output name=repo::${GITHUB_REPOSITORY#$GITHUB_REPOSITORY_OWNER/}
      - name: Get Branch Name
        id: branch
        run: echo ::set-output name=branch::${{ github.head_ref }}
      - name: Install JQ
        run: |
          sudo apt-get update
          sudo apt-get install jq
      - name: Compare Branches
        id: branch-compare
        run: |
          result=$(curl --location 'http://localhost:3001/${{ steps.repo.outputs.repo }}/${{ steps.branch.outputs.branch }}/compare' \
            --header 'x-organization-uuid: ${{ secrets.ORGANIZATION_UUID }}')
          parsed_result=$(echo "$result" | jq .)
          echo "::set-output name=parsed_result::$parsed_result"
      - name: Comment on PR
        uses: actions/github-script@v7
        with:
          script: |
            const prs = await github.rest.repos.listPullRequestsAssociatedWithCommit({
              owner: context.repo.owner,
              repo: context.repo.repo,
              commit_sha: context.sha
            })

            const i = prs.data.length ? prs.data?.[0].number : null

            if (!i) {
              return
            }
            github.rest.issues.createComment({
              issue_number: i,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `Branch comparison results: ${context.payload.workflow_run.outputs.parsed_result}`
            })
