name: Upload Test Results

on:
  workflow_call:
    inputs:
      resultType:
        description: 'Type of result'
        type: string
        required: true
      artifactName:
        description: 'Artifact name'
        type: string
        required: true
      testFile:
        description: 'Test file path'
        type: string
        required: true

jobs:
  upload-test-results:
    name: Upload Test Results
    runs-on: self-hosted
    steps:
      - name: Get Repo Name
        id: repo
        run: echo ::set-output name=repo::${GITHUB_REPOSITORY#$GITHUB_REPOSITORY_OWNER/}
      - name: Get Branch Name
        id: branch
        run: | # Determine branch name based on the event that triggered the workflow
          if [[ "${{ github.ref }}" == "refs/pull/"* ]]; then
            echo ::set-output name=branch::${{ github.head_ref }}
          else
            echo ::set-output name=branch::${GITHUB_REF#refs/heads/}
          fi
      - name: Download Test Results
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.artifactName }}
          path: results
      - name: Upload Test Results
        run: |
          curl --location 'http://localhost:3001/${{ steps.repo.outputs.repo }}/${{ steps.branch.outputs.branch }}/${{ inputs.resultType }}' \
            --header 'x-organization-uuid: ${{ secrets.ORGANIZATION_UUID }}' \
            --form 'file=@results/${{ inputs.testFile }}'