name: Upload Test Results

on:
  workflow_call:
    inputs:
      repo:
        description: 'Repository name'
        required: true
      ref:
        description: 'Github ref'
        required: true
      organizationUuid:
        description: 'Organization UUID'
        required: true
      artifactName:
        description: 'Artifact name'
        required: true
      testFile:
        description: 'Test file path'
        required: true

jobs:
  upload-results:
    name: Upload Results
    runs-on: self-hosted
    steps:
      - name: Get Branch Name
        id: branch
        run: echo ::set-output name=branch::${GITHUB_REF#refs/heads/}
      - name: Download Test Results
        uses: actions/download-artifact@v3
        with:
          name: ${{ github.event.inputs.artifactName }}
          path: results
      - name: Upload Test Results
        run: |
          curl --location 'http://localhost:3001/${{ github.event.inputs.repo }}/${{ steps.branch.outputs.branch }}/tests' \
            --header 'x-organization-uuid: ${{ github.event.inputs.organizationUuid }}' \
            --form 'file=@results/${{ github.event.inputs.testFile }}'