name: Run Tests

on:
  workflow_dispatch:
  push:

env:
  ORGANIZATION_UUID: ${{ secrets.ORGANIZATION_UUID }}

jobs:
  run-tests:
    name: Run Tests
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Dependencies
        run: npm install && cd backend && npm install
      - name: Run Tests
        run: npm test
        continue-on-error: true
      - name: Upload Test Results
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: results

  upload-results:
    name: Upload Results
    uses: ./.github/workflows/call-upload-results.yaml
    with:
      repo: ${{ github.repository }}
      ref: ${{ github.ref }}
      artifactName: test-results
      testFile: unit.xml
    secrets: inherit